### ISSUE TITLE
How many prototypes are actually set?

### ISSUE THREAD

**Issue by mu-cai** [heliossun/SQ-LLaVA#2]
Good work!

Several questions:

1. How many prototypes are actually set?
2. The SQ is just that with probability 0.3, the question itself will have the next token prediction loss?

**Comment by heliossun** [comment]
> Good work!
> 
> Several questions:
> 
>     1. How many prototypes are actually set?
> 
>     2. The SQ is just that with probability 0.3, the question itself will have the next token prediction loss?

1. We set the number of prototypes to 256.
2. We randomly unmask 30% - 50% of all questions to train the LLM with the next token prediction loss.
