### ISSUE TITLE
 pre-trained model you provided is not working

### ISSUE THREAD

**Issue by 258863** [heliossun/SQ-LLaVA#4]
Hello! I'm wondering why the link to the pre-trained model you provided is not working. I tried accessing it, but it seems there's an issue. Could you please check if the link is valid or provide me with a new one? Thank you very much for your help!

**Comment by heliossun** [comment]
Sorry for the confusion. Please check again. We have updated the link.

**Comment by 258863** [comment]
> Sorry for the confusion. Please check again. We have updated the link.
Thank you for your answer. I rechecked [Model Zoo](https://github.com/heliossun/SQ-LLaVA/blob/main/docs/MODEL_ZOO.md) and found the complete model configuration.
