### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by sssssshf** [heliossun/SQ-LLaVA#5]
请问最小 gpu大概多少啊..2*32G可以训练吗

**Comment by sssssshf** [comment]
![image](https://github.com/user-attachments/assets/f67d73f4-bce3-437d-a0c9-0d9d1c39f9de)
这个的运行demo在那在哪里啊 有没有运行的demo教程

**Comment by heliossun** [comment]
> 请问最小 gpu大概多少啊..2*32G可以训练吗

Yes, you can.

**Comment by heliossun** [comment]
> ![image](https://private-user-images.githubusercontent.com/68574922/362168340-f67d73f4-bce3-437d-a0c9-0d9d1c39f9de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTY3NzIsIm5iZiI6MTcyNDg1NjQ3MiwicGF0aCI6Ii82ODU3NDkyMi8zNjIxNjgzNDAtZjY3ZDczZjQtYmNlMy00MzdkLWEwYzktMGQ5ZDFjMzlmOWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE0NDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjRkNDk0NDdjNjliNmM3Y2FmNzhjYTVkYWQ3N2YwNTBkNTJiMTY4MWU0ZTc2YTBmYjljOWJkZDA3NzdkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cT3cHbWAioTVglLzjpg-CkR1eXAF4-IkpNNZHro19k4) 这个的运行demo在那在哪里啊 有没有运行的demo教程

We've uploaded a demo code. Thank you!

**Comment by sssssshf** [comment]
> > ![image](https://private-user-images.githubusercontent.com/68574922/362168340-f67d73f4-bce3-437d-a0c9-0d9d1c39f9de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTY3NzIsIm5iZiI6MTcyNDg1NjQ3MiwicGF0aCI6Ii82ODU3NDkyMi8zNjIxNjgzNDAtZjY3ZDczZjQtYmNlMy00MzdkLWEwYzktMGQ5ZDFjMzlmOWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE0NDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjRkNDk0NDdjNjliNmM3Y2FmNzhjYTVkYWQ3N2YwNTBkNTJiMTY4MWU0ZTc2YTBmYjljOWJkZDA3NzdkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cT3cHbWAioTVglLzjpg-CkR1eXAF4-IkpNNZHro19k4) 这个的运行demo在那在哪里啊 有没有运行的demo教程
> 
> We've uploaded a demo code. Thank you!

y提供的demo里 运行文件包含了model_path model_base lora_pretrain.请问model zoom里面下载的是属于哪个呢.剩下的 模型在哪下载呢  这是下载的权重 tree
![image](https://github.com/user-attachments/assets/a7763206-9061-4ad0-9a48-16c458e64d29)

运行的sh文件该如何填写这个路径呢
CUDA_VISIBLE_DEVICES=0 python visual_questioning.py \
  --model_path \
  --model_base \
  --conv-mode="v1_sq" \
  --lora_pretrain = \
  --n_shot 3
